language: node_js
before_script:
  - sleep 15
os:
  - linux
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4"
  - "stable"
services:
  - mongodb
env:
  - secure: aJ59EajEAXSNW3Ol/ysdxBnGbgIK+PX09yq80w+YQMh75VYbQQ86usAv0fxEg+R4JhaLmwePOtfYuNNvRPj3f8qyRX7uZ1rPlX3xkv9vXKdoc/lSZTVZY+OyFONcvvkypI40Uqi1/upaOPJ0e7UWe8i5RC7KSkC425QjfLF1IwE=
after_success: npm run codeclimate
