language: node_js
before_script:
  - sleep 15
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
env:
  - secure: Jia6JOXXSMPilgEpHts5qD+H5ilDU/ANrwJCSt225uMRB3sDPVw/b8g4/xeOmIsK44sIf2H4Lz5eTs62SlL1mh4dsz6m4g7sgz2AlWSN5hwsAeCNzTnrY/j49FoieliEzBmkAJelmnV7tw6bejkxPjBJpce6Wt8mLir5EGhH1zA=
after_success: npm run codeclimate
