language: node_js
before_script:
  - sleep 15
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
env:
  - secure: oy+ySKIuQqsC2c2JmPGGn9iZpaLWNmLFhrvtKr3zpoVV0F8XYQq4bCtUO2vE1PuGR/0cr90c40o1caT9qNK2nqMLw7QSXY+VsU8Zlnu1yz7kONi81eXucUedGvX0jqPVd6EXn26jpetofRUd2y/cyqtuEmpPneosivpeA341Of4=
after_success: npm run codeclimate
